### ISSUE TITLE
Todo: login and user management

### ISSUE THREAD

**Issue by Telsak** [Telsak/podbooking#1]
- [x] Add user login and authentication (initially just run with local table for this)
- [x] Separate role for customer and admin (student/teacher)
- [x] admin has a panel for user management 
- [x] change admin panel to ensure changing password writes the hash and not the PT
